language: go
go:
  - 1.5
  - tip
install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get github.com/tools/godep
  - godep restore ./...
script:
  - go test -v ./...
  - go vet -x ./...
notifications:
  slack:
    secure: hfbwCnF2U61Gm9nVa7yXrp7QxeZC8cOxAziYTRxIJ/tUaC65QNLS7q6AMdyKTRLOwIffgKkVC9Jw1XcM8FxudOS85qWBCoysxbHvgNWkUczQVaxkR2EKEiQQdTNqrHYc/U84X6F+vupEqQGJM7SlSXnNoo/JsNDqFCAPVqDUJyz8o+1Km5aSGxspZUrs4ywNfreFB/g5qWWeedCIorVY5o34Y1IYZJ9R0dLOI9aXeAqTKr3KWXlZJD5DqIGwvy2fB+nzvyJALC+uHKbxMq/8sjSNeV4/4tSJSKKuokYpMIx2tTQzra3o2+M/CimyhNZxlzmI0X7n+t10oqX2pYjSdjxK9WJ0ZjiR0pUf1z7JfPS8qj70SkM2+n5BuiIrRF7lSBaXA/IyOV443PJqoLO8JG7ZXHIcYriGQe23K4eFZnDbJUrlqZr0OeHYh09nCRk43BfwoGNlAZJbHGcmsoHiz4v5GN0cEOU+83yW/aTYJ0uCL4PHDG0TqLsKsMPMZbmQ0WsKTEdJm4yl/qgcaMkxKVL+8lcjgmBbuz4NEaHwAgki+RZQ2B/V9ilK6QkPb8/EdJ2ZBwKlUR98iSxSGOCco3jMOTE1VhE5Kahty6K6HvSDXnozqU3ja7TM5ek+o7afRaMjM0bcOrmj9+tpH1cXTA6mPfXsbFLQ2wkouRJUPdc=
